-- AlterTable
ALTER TABLE "Character" ADD COLUMN     "attack" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "critChance" DOUBLE PRECISION NOT NULL DEFAULT 0.05,
ADD COLUMN     "critDamage" DOUBLE PRECISION NOT NULL DEFAULT 1.1,
ADD COLUMN     "defense" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "luck" INTEGER NOT NULL DEFAULT 5;

-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "bonusAtack" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonusCrit" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonusHp" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonusLuck" INTEGER NOT NULL DEFAULT 0;
